import chalk from "chalk";
import { Command } from "commander";
import { runEngineCommand } from "../engine-degrade.js";
import type { TreatmentSessionLauncherContract } from "../../core/lazy-module-contracts.js";

/** Loaded lazily; the public package degrades honestly when it is absent. */
const TREATMENT_SESSION_LAUNCHER_MODULE = "../../engine/treatment-session-launcher.js";

interface LaunchTreatmentSessionOptions {
  applyDir?: string;
  out?: string;
  seed?: string;
  projectDir?: string;
}

/**
 * `compaction launch-treatment-session --apply-dir <dir> [--out <script>] [--seed <file>] [--project-dir <dir>]`
 *
 * Prepares (WRITES) an executable launch script for a FRESH seeded Claude Code session, the Lane B
 * treatment arm. It NEVER starts the session itself and NEVER spawns `claude`; YOU run the script.
 *
 * Reuses the EXACT approval gates of `export-session-seed` (valid `approved_for_in_workflow_use` record,
 * approved-context present + hash-matched, retained original present + hash-matched). Refuses otherwise -
 * no script written, exit non-zero. If `session-seed.md` is absent it is generated by REUSING
 * `exportSessionSeed`; if present it is reused unchanged. Read-only over apply artifacts except for the
 * new script (and the seed only when generated). No provider call, no network, no global config changes.
 */
export function registerLaunchTreatmentSessionCommand(program: Command): void {
  program
    .command("launch-treatment-session")
    .description(
      "Prepare (WRITE, never run) an executable launch script for a FRESH seeded Claude Code session - Lane B treatment arm (TREATMENT SETUP, NOT billing-confirmed savings; operator-invoked, NOT auto-apply). Refuses unless approved + hashes match. Never spawns claude; never touches global config."
    )
    .requiredOption("--apply-dir <dir>", "The apply-context artifacts directory (must contain an approval record)")
    .option("--out <script>", "Where to write the launch script (default: <apply-dir>/launch-treatment-session.sh)")
    .option("--seed <file>", "Path to the session seed to read/generate (default: <apply-dir>/session-seed.md)")
    .option("--project-dir <dir>", "Project directory the launched session runs in (default: current directory)")
    .action(async (options: LaunchTreatmentSessionOptions) => {
     await runEngineCommand(async () => {
      // The treatment-session launcher is internal methodology (engine). Lazy-load it; degrades
      // honestly when the engine build is excluded from the package.
      const { prepareTreatmentSessionLauncher } = (await import(
        TREATMENT_SESSION_LAUNCHER_MODULE
      )) as TreatmentSessionLauncherContract;

      console.log(chalk.cyan("compaction launch-treatment-session (Lane B treatment setup)"));
      console.log(
        "Operator-invoked, NOT auto-apply. This command only WRITES a launch script; it starts no session and spawns no process. No provider call, no network."
      );

      const result = await prepareTreatmentSessionLauncher({
        applyDir: options.applyDir!,
        outScript: options.out,
        seedFile: options.seed,
        projectDir: options.projectDir
      });

      if (result.refused) {
        console.error(chalk.red("Refused - no launch script written:"));
        for (const reason of result.reasons) {
          console.error(chalk.red(`- ${reason}`));
        }
        process.exitCode = 1;
        return;
      }

      console.log(result.consoleSummary);
      console.log(chalk.green(`Wrote ${result.scriptPath}`));
      console.log(chalk.yellow(`Run it yourself when ready: bash ${result.scriptPath}`));
     });
    });
}
